"""Central discovery catalog ORM models — stored in ``catalog.db``.

Tracks only available datasets. File-level metadata lives in
per-dataset ``catalog_<name>.db`` files defined in ``.dataset``.
"""

from sqlalchemy import Column, Integer, Sequence, String
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    """Base class for central catalog ORM models."""

    pass


class Dataset(Base):
    """ORM model for the datasets table — central registry of available
    datasets.

    Parameters
    ----------
    id : int, optional
        Primary key (auto-generated by sequence).
    name : str
        Unique short name for the dataset.
    long_name : str
        Human-readable full name.
    description : str, optional
        Optional description of the dataset contents.
    """

    __tablename__ = "datasets"
    __table_args__: tuple = ({"schema": "pysus"},)

    id = Column(
        Integer,
        Sequence("datasets_id_seq", schema="pysus"),
        primary_key=True,
    )
    name = Column(String, nullable=False, unique=True, index=True)
    long_name = Column(String, nullable=False)
    description = Column(String, nullable=True)

    def __repr__(self):
        return self.name
