default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [--line-length=80]
        exclude: ^docs/|^pysus/http/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=80]
        exclude: ^.*/js/.*$|^pysus/http/

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=80, --extend-ignore=E203]
        exclude: ^docs/|^pysus/http/
        additional_dependencies: [
            'flake8-blind-except==0.2.1',
            'flake8-bugbear==24.2.6',
            'flake8-comprehensions==3.14.0',
            'flake8-implicit-str-concat==0.4.0',
            'pydocstyle==6.3.0',
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [
            'types-python-dateutil>=2.9.0',
            'types-requests>=2.31.0',
            'types-setuptools>=69.0.0',
            'pandas-stubs>=2.2.0',
            'pydantic>=2.0.0',
        ]
        args: [--ignore-missing-imports, --explicit-package-bases]
        exclude: ^docs/|^pysus/http/

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
