name: env-pysus
channels:
  - conda-forge
dependencies:
  - pandas
  - cffi>=1.0.0
  - dbfread
  - gdal=3.3.3
  - scipy=1.7.1
  - geocoder
  - requests
  - folium
  - fastparquet
  - geopandas
  - dask
  - wget
  - colorcet
  - datashader
  - xarray
  - georasters
  - elasticsearch
  - pyarrow
  # dev
  - pip
  - flake8
  - coverage
  - sphinx
  - pandas
  - pytest
  - pytest-cov
  - pre-commit
  - libpq

  - pip:
    - geobr
    - facets-overview
    # - pysus
