name: pysus
channels:
  - conda-forge
  - defaults
dependencies:
  - setuptools
  - python>=3.11
  - numpy>=1.26.2
  - cffi
  - gcc
  - make
  - poetry>=1.3.2
  - pip
  - pip:
    - shapely==1.8.5.post1 # Pinning Shapely version to resolve third-party dependency issues