name: env-pysus
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cffi
  - docker-compose
  - gcc
  - make
  - pip
  - psycopg2
  - python 3.11.*
  - poetry >= 1.3.2
  - pip:
    - urllib3 ==1.26.15
    - requests
    - pandas
    - sqlalchemy
