name: pysus
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - numpy=1.26
  - cffi
  - gcc
  - make
  - pip
  - poetry>=1.3.2
  - pip:
    # Pinning Shapely version to resolve third-party dependency issues
    - shapely==1.8.5.post1