name: env-pysus
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cffi
  - docker-compose
  - gcc
  - make
  - pip
  - poetry
  - psycopg2
  - python 3.9.*
  - poetry
  - pip:
    - urllib3
    - requests
