{% set name = "PySUS" %}
{% set version = "0.5.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 34dab521bdd8f680d8927fa355f261232d6c122901a2726f0412f472b831066b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - cffi >=1.0.0
    - dbfread
    - fastparquet
    - geocoder
    - pandas
    - pip
    - pyarrow
    - python
    - requests
    - georasters
  run:
    - cffi >=1.0.0
    - dbfread
    - fastparquet
    - geocoder
    - pandas
    - pyarrow
    - python
    - requests
    - georasters

test:
  imports:
    - pysus
    - pysus.demography
    - pysus.online_data
    - pysus.preprocessing
    - pysus.tests
    - pysus.tests.test_data

about:
  home: "https://github.com/fccoelho/PySUS"
  license: gpl-v3
  license_family: GPL3
  license_file: 
  summary: "Tools for dealing with Brazil's Public health data"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - fccoelho
