name: release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry

    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Test release
      if: ${{ github.event_name != 'workflow_dispatch' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make release-dry

    - name: Release
      if: ${{ github.event_name == 'workflow_dispatch' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry config pypi-token.pypi ${PYPI_TOKEN}
        make release

  docs:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        environment-file: conda/dev.yaml
        channels: conda-forge,nodefaults
        activate-environment: pysus
        auto-update-conda: true
        conda-solver: libmamba

    - name: Install dependencies
      run: |
        pip install poetry poetry-plugin-export
        poetry config virtualenvs.create false
        poetry install --with docs --extras dbc

    - name: Build docs
      run: |
        cd docs
        make html

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build/html

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4
